[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name ="office_tools"
version = "0.0.1"
dependencies = [
    "docxtpl>=0.16.7",
    "pytest>=7.4.0",
    "pywin32",
    "xlrd>=2.0.1",
    "openpyxl>=3.1.2",
    "docx2pdf>=0.1.8",
    "pandas>=2.1.1",
    "pysimplegui>=4.53.0",
]