[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name ="office_tools"
version = "0.0.1"
dependencies = [
    "docxtpl",
    "pytest",
    "pywin32",
    "xlrd",
    "openpyxl",
    "docx2pdf",
    "pandas",
    "pysimplegui",
]