name: Office Tools CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        python-version: [ 3.11.2 ]
    env:
      ANENV: 'a variable'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ..requirements.txt

      - name: Run tests
        run: python -B -m pytest

