name: Staged Auto-Merge

on:
  push:
    branches:
      - staged

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        python-version: [ 3.11.2 ]
    env:
      ANENV: 'a variable'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ..\requirements-dev.txt

#      - name: Type Checks
#        run : mypy --install-types .

      - name: Run tests
        run: python -B -m pytest



  create-pull-request:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          title: 'Automated PR from Staged'
          body: 'Please review the changes in this PR.'

  auto-merge:
    needs: create-pull-request
    runs-on: windows-latest
    steps:
      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
